import type { Metadata } from "next";
import { inter } from "@/fonts";
import "./globals.css";
// import { PopupContext } from "@/context/PopapContext";
import Metrics from "@/components/Metrics"; // 1. Импортируем новый компонент

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {children}
        <Metrics />
      </body>
    </html>
  );
}